<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyName>HIP2Json.CLI</AssemblyName>
    <RootNamespace>HIP2Json.CLI</RootNamespace>
    <AssemblyTitle>HIP2Json.CLI</AssemblyTitle>
    <Product>HIP2Json.CLI</Product>
    <Copyright>Copyright © Aiden 2025</Copyright>
    <CurrentDate>$([System.DateTime]::Now.ToString("yyyy.MM.dd"))</CurrentDate>
    <AssemblyVersion>$(CurrentDate)</AssemblyVersion>
    <FileVersion>$(CurrentDate)</FileVersion>
    <Version>$(CurrentDate)</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HIP2Json\HIP2Json.csproj" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>